### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gaoyajian** [dirkphilip/LASIF_2.0#47]
Generating input files for event 1 of 116 -- 2410946_2007test
Segmentation fault (core dumped)

hey cool guys, here I confronted with segmentation fault running the lasif generate_input_files ..., have you any ideas about that? Thanks!

**Comment by solvithrastar** [comment]
Hey!  Can you show us the command you used when you got the error?
"lasif generate_input_files..."
