### ISSUE TITLE
MPI: undefined symbol error

### ISSUE THREAD

**Issue by deborahwehner** [dirkphilip/LASIF_2.0#59]
Hi,

when trying to install LASIF 2.0 based on your github instructions I get the following error (in a fresh environment):

**ImportError: .../miniconda3/envs/TEST/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-x86_64-linux-gnu.so: undefined symbol: MPI_Type_create_f90_integer**

when carrying out  

**python -c "import pyasdf; pyasdf.print_sys_info()"**
and/or
**py.test**

based on the following installation lines:

# re-install it using pip
**$ pip install mpi4py**
# Install a parallel version of hdf5
**$ conda install -c spectraldns h5py-parallel**

It was working fine several weeks ago - were there some changes or may it interfere with the integrated Salvus MPI I installed later on (in a separate env though)? 

Cheers,
Debby

**Comment by solvithrastar** [comment]
Hi Debby, sorry for the (very) late response.

We are now starting to make a more stable version of Lasif that should fix all these issues. As a quick fix you probably do not need the parallel h5py right now so you can just install the regular h5py and everything should work within Lasif. There might be some problems in the communication with Salvus when it comes to MPI related things. 

We will make sure all of this works properly as soon as possible and then we'll update the installation instructions and all of that.

Cheers,
Sölvi

**Comment by deborahwehner** [comment]
Thanks, Sölvi!

When trying to run LASIF with the regular h5py I ran into problems such as:
**module 'h5py' has no attribute 'get_config'** or **'Group'** etc. (when running the test or initializing a project)

It also seems like **conda install/uninstall mpi4py** includes h5py-parallel

Do you have any idea for a quick fix to get LASIF 2.0 work with the recent Salvus version? Do you have an estimated time frame on when the stable Lasif version will be out?

Cheers,
Debby
