### ISSUE TITLE
Refactoring of `absorbing_boundaries_in_km` into `simulation_settings` was incomplete

### ISSUE THREAD

**Issue by larsgeb** [dirkphilip/LASIF_2.0#78]
In a recent commit the `absorbing_boundaries_in_km` was refactored from `salvus_settings` into `simulation_settings`. This was reflected in the following line change of the `create_salvus_forward_simulation` method in the `salvus_utils` module.

https://github.com/dirkphilip/LASIF_2.0/blob/66b7051ac5f1758d2f6a2b0b1b434fed9d731ee4/lasif/salvus_utils.py#L103

However, a few lines further, this variable is used again, and taken from the old dictionary:
https://github.com/dirkphilip/LASIF_2.0/blob/66b7051ac5f1758d2f6a2b0b1b434fed9d731ee4/lasif/salvus_utils.py#L107-L109

This raises an exception when the used mesh is not global. Simple refactor would be sufficient, but I'll put that burden on the original muppet who introduced the bug, @solvithrastar .

**Comment by solvithrastar** [comment]
Dear Lars,
This should be solved in the latest pull request, pending approval by Dirk-Philip.
All the best,
Sölvi
