### ISSUE TITLE
LASIF without Salvus

### ISSUE THREAD

**Issue by dsiervo** [dirkphilip/LASIF_2.0#91]
Hi, I want to use LASIF but I wasn't able to install Salvus because it is subject to licensing fees that I can't afford right now.

Is there a tutorial on using LASIF with a solver other than Salvus?

**Comment by dirkphilip** [comment]
Hi,

We currently do not support any other solvers than Salvus. In principle, it
should be fairly easy to
adapt some of the functions for use with other solvers, so you could also
try giving that a shot.

For what kind of project are you planning to use it? Did you talk to the
Salvus developers already about a license?

Best wishes,
Dirk-Philip

**Comment by solvithrastar** [comment]
Hi,

Feel free to contact me: soelvi.thrastarson@erdw.ethz.ch and explain how you want to use LASIF. I can give you some more detailed instructions on how you can do it.

All the main LASIF functionalities work without Salvus, it's just not as streamlined. So feel free to be in contact.

Cheers,
Sölvi
